/**
 * GENERATED by Blume compiler — do not edit by hand.
 * Spec: join-live-match@v1
 * Seed: abcdef0123456789
 * Compiled: 2026-09-16T05:21:19.214Z
 */
import { test, expect } from "@playwright/test";

const concrete = {
  "matchId": "match-7001",
  "userId": "user-70001",
  "viewerCount": 2,
  "otherUserId": "user-alt-1"
} as const;

test("AC-01 — Spectator joins successfully", async ({ page }) => {
  void concrete;
  // Setup: a live match is in progress; User is authenticated; A live match exists and is joinable
  // Preconditions must already hold in the test environment.
  await page.getByRole("button", { name: "Join" }).click();
  await expect(page.getByTestId("board")).toBeVisible({ timeout: 2000 });
  await expect(page.getByTestId("viewer-count")).toBeVisible();
  {
    const box = await page.getByRole("button", { name: "Join" }).boundingBox();
    expect(box).not.toBeNull();
    const viewport = page.viewportSize();
    expect(viewport).not.toBeNull();
    if (box && viewport) {
      expect(box.x).toBeGreaterThanOrEqual(0);
      expect(box.y).toBeGreaterThanOrEqual(0);
      expect(box.x + box.width).toBeLessThanOrEqual(viewport.width);
      expect(box.y + box.height).toBeLessThanOrEqual(viewport.height);
    }
  }
});

test("AC-02 — Match ends while spectating", async ({ page }) => {
  void concrete;
  // Setup: the user is spectating a live match; User is authenticated; A live match exists and is joinable
  // Preconditions must already hold in the test environment.
  await page.waitForTimeout(2000); // the match ends
  await expect(page.getByText("Match complete")).toBeVisible();
  await expect(page.getByRole("link", { name: "Results" })).toBeVisible();
});

test("EC-01 — Match becomes full mid-join", async ({ page }) => {
  void concrete;
  // Setup: the match reaches max spectators as the user taps "Join"; User is authenticated; A live match exists and is joinable
  // Preconditions must already hold in the test environment.
  await page.waitForTimeout(2000); // the join request completes
  await expect(page.getByText("Match is full")).toBeVisible();
  await expect(page.getByTestId("similar-matches")).toBeVisible();
});

test("EC-02 — Network drops during join", async ({ page }) => {
  void concrete;
  // Setup: the user taps "Join"; User is authenticated; A live match exists and is joinable
  // Preconditions must already hold in the test environment.
  await page.waitForTimeout(2000); // the network request times out
  await expect(page.getByRole("button", { name: "Retry" })).toBeVisible();
  // Assert no partial join/mutation left behind: no partial join state is left behind
});

test("COMPOSED — End-to-end composed journey", async ({ page }) => {
  void concrete;
  // Setup: a live match is in progress; User is authenticated; A live match exists and is joinable
  // Preconditions must already hold in the test environment.
  await page.getByRole("button", { name: "Join" }).click();
  await expect(page.getByTestId("board")).toBeVisible({ timeout: 2000 });
  await expect(page.getByTestId("viewer-count")).toBeVisible();
  {
    const box = await page.getByRole("button", { name: "Join" }).boundingBox();
    expect(box).not.toBeNull();
    const viewport = page.viewportSize();
    expect(viewport).not.toBeNull();
    if (box && viewport) {
      expect(box.x).toBeGreaterThanOrEqual(0);
      expect(box.y).toBeGreaterThanOrEqual(0);
      expect(box.x + box.width).toBeLessThanOrEqual(viewport.width);
      expect(box.y + box.height).toBeLessThanOrEqual(viewport.height);
    }
  }
  await page.waitForTimeout(2000); // the match ends
  await expect(page.getByText("Match complete")).toBeVisible();
  await expect(page.getByRole("link", { name: "Results" })).toBeVisible();
});
