/**
 * GENERATED by Corin compiler — do not edit by hand.
 * Spec: match-join-endpoint@v1
 * Seed: c0ffee00deadbeef
 * Compiled: 2026-09-16T04:55:07.009Z
 */
import { test, expect } from "@playwright/test";

const concrete = {
  "matchId": "match-6080",
  "userId": "user-78080",
  "viewerCount": 1,
  "otherUserId": "user-9424"
} as const;

test("AC-01 — Successful join", async ({ request }) => {
  void concrete;
  // Setup: a live match under capacity
  const fixture = {"matchId":"match-6080","userId":"user-78080"} as const;
  void fixture;
  const response = await request.post("/matches/match-6080/join", { data: {"userId":"user-78080"} });
  expect(response.status()).toBe(200);
  // Body expectation from spec: the viewer count increments by 1
  const body = await response.json();
  expect(body).toBeTruthy();
});

test("EC-01 — Match at capacity", async ({ request }) => {
  void concrete;
  // Setup: the match is at max viewers
  const fixture = {"matchId":"match-6080","userId":"user-78080"} as const;
  void fixture;
  const response = await request.post("/matches/match-6080/join", { data: {"userId":"user-78080"} });
  expect(response.status()).toBe(409);
  // Assert no partial join/mutation left behind: viewer count does not increment
});
