/**
 * GENERATED by Corin compiler — do not edit by hand.
 * Spec: match-join-endpoint@v1
 * Seed: a485609c6aef6bd3
 * Compiled: 2026-09-16T05:21:20.633Z
 */
import { test, expect } from "@playwright/test";

const concrete = {
  "matchId": "match-4444",
  "userId": "user-94444",
  "viewerCount": 5,
  "otherUserId": "user--62679"
} as const;

test("AC-01 — Successful join", async ({ request }) => {
  void concrete;
  // Setup: a live match under capacity
  const fixture = {"matchId":"match-4444","userId":"user-94444"} as const;
  void fixture;
  const response = await request.post("/matches/match-4444/join", { data: {"userId":"user-94444"} });
  expect(response.status()).toBe(200);
  // Body expectation from spec: the viewer count increments by 1
  const body = await response.json();
  expect(body).toBeTruthy();
});

test("EC-01 — Match at capacity", async ({ request }) => {
  void concrete;
  // Setup: the match is at max viewers
  const fixture = {"matchId":"match-4444","userId":"user-94444"} as const;
  void fixture;
  const response = await request.post("/matches/match-4444/join", { data: {"userId":"user-94444"} });
  expect(response.status()).toBe(409);
  // Assert no partial join/mutation left behind: viewer count does not increment
});
