#!/usr/bin/env bash
#
# Cloud Agent install phase for Blume.
#
# Idempotent, terminating repository bootstrap. Prepares durable state:
#   - system Postgres (Blume uses Neon in the cloud; locally we run a plain
#     Postgres behind a tiny Neon-HTTP proxy so the same app code runs)
#   - node dependencies
#   - a local Postgres data directory
#   - out-of-repo deps for the dev-only Neon proxy (pg, ws)
#   - Clerk keys (uses provided secrets, else provisions a keyless dev app)
#   - local .env / .env.local for dev
#
# Per-boot process startup lives in .cursor/start.sh, not here.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

PGDATA="${BLUME_PGDATA:-$HOME/blume-pgdata}"
DEV_DEPS_DIR="$HOME/.blume-dev"

echo "==> Installing system packages (postgresql)"
if ! command -v /usr/lib/postgresql/*/bin/postgres >/dev/null 2>&1 && \
   ! ls /usr/lib/postgresql/*/bin/postgres >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi
PGBIN="$(dirname "$(ls /usr/lib/postgresql/*/bin/postgres | sort -V | tail -1)")"
echo "    using $PGBIN"

echo "==> Installing node dependencies (npm ci)"
npm ci

echo "==> Initializing local Postgres cluster (idempotent)"
if [ ! -f "$PGDATA/PG_VERSION" ]; then
  mkdir -p "$PGDATA"
  "$PGBIN/initdb" -D "$PGDATA" -U postgres --auth=trust >/dev/null
fi

echo "==> Installing dev-only Neon proxy deps (pg, ws) out-of-repo"
mkdir -p "$DEV_DEPS_DIR"
if [ ! -d "$DEV_DEPS_DIR/node_modules/pg" ] || [ ! -d "$DEV_DEPS_DIR/node_modules/ws" ]; then
  ( cd "$DEV_DEPS_DIR" && npm install --no-save --no-package-lock pg@8 ws@8 >/dev/null 2>&1 )
fi

echo "==> Writing local .env (gitignored)"
if [ ! -f .env ]; then
  AUTH_SECRET="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Local dev (gitignored) — generated by Cloud Agent environment setup.
BLUMEDB_DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/blume
BLUMEDB_DATABASE_URL_UNPOOLED=postgres://postgres:postgres@127.0.0.1:5432/blume
BLUME_DEFAULT_PROJECT_SLUG=carromlive
AUTH_SECRET=$AUTH_SECRET
EOF
fi

echo "==> Ensuring Clerk keys are available"
# Prefer real keys supplied as secrets; otherwise provision a keyless dev app
# (no Clerk account required). Keys live in .env.local (gitignored).
if [ -n "${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}" ] && [ -n "${CLERK_SECRET_KEY:-}" ]; then
  if ! grep -q "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" .env.local 2>/dev/null; then
    cat > .env.local <<EOF
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
CLERK_SECRET_KEY=$CLERK_SECRET_KEY
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=/
NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=/
EOF
  fi
elif ! grep -q "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" .env.local 2>/dev/null; then
  echo "    no Clerk secrets set — provisioning a keyless dev app"
  npx --yes clerk@latest init --accountless --no-skills --yes < /dev/null >/dev/null 2>&1 || \
    echo "    WARN: keyless provisioning failed (set Clerk secrets to fix)"
  # The CLI scaffolds top-level sign-in/up pages; Blume already ships its own
  # under app/(portal)/app, so drop the duplicates it creates.
  rm -rf app/sign-in app/sign-up
fi

echo "==> Install complete"
