/**
 * Self-check for the compiler's deterministic api path.
 * Run: npm run compile:selfcheck
 */
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { compileSpec, parseSpecMarkdown } from "./index";

const main = async () => {
  const root = process.cwd();

  const uiRaw = readFileSync(
    join(root, "specs/features/join-live-match.md"),
    "utf8"
  );
  const ui = parseSpecMarkdown(uiRaw);
  assert.equal(ui.id, "join-live-match");
  assert.equal(ui.layer, "ui");
  assert.equal(ui.acceptance_criteria.length, 2);
  assert.equal(ui.acceptance_criteria[0].id, "AC-01");
  assert.equal(ui.acceptance_criteria[0].criticality, "critical");
  assert.equal(ui.trailing.type, "ui_states");
  assert.ok(ui.edge_cases[0].ref === "AC-01");

  const api = await compileSpec("match-join-endpoint", {
    seed: "c0ffee00deadbeef",
  });
  assert.equal(api.intermediate.seed, "c0ffee00deadbeef");
  assert.ok(api.intermediate.scenarios.some((s) => s.id === "AC-01"));
  assert.ok(api.intermediate.scenarios.some((s) => s.id === "EC-01"));
  assert.ok(
    api.intermediate.scenarios
      .find((s) => s.id === "AC-01")
      ?.steps.some((s) => s.action === "http" && s.method === "POST")
  );
  assert.ok(existsSync(api.paths.playwright));
  assert.ok(existsSync(api.paths.intermediateJson));

  const pw = readFileSync(api.paths.playwright, "utf8");
  assert.match(pw, /GENERATED by Blume compiler/);
  assert.match(pw, /expect\(response\.status\(\)\)\.toBe\(200\)/);
  assert.match(pw, /expect\(response\.status\(\)\)\.toBe\(409\)/);

  const uiCompile = await compileSpec("join-live-match", {
    seed: "abcdef0123456789",
  });
  assert.ok(existsSync(uiCompile.paths.playwright));
  assert.ok(uiCompile.paths.maestro.length >= 1);
  assert.ok(
    uiCompile.intermediate.scenarios.some((s) => s.kind === "composed"),
    "ui specs with 2+ ACs must emit a composed journey"
  );

  // a11y-tree resolution path
  const withTree = await compileSpec("join-live-match", {
    seed: "abcdef0123456789",
    resolver: "llm",
    a11yTree: {
      role: "main",
      children: [
        { role: "button", name: "Join", testId: "join-btn" },
        { role: "img", name: "board", testId: "board" },
      ],
    },
    irOnly: true,
  });
  assert.ok(withTree.intermediate.scenarios.length >= 2);

  console.log("compiler selfcheck passed");
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
