import type { IntermediateForm, IntermediateAction, ResolvedTarget } from "../types";

const maestroSelector = (resolved?: ResolvedTarget, fallback = ""): string => {
  if (!resolved || resolved.strategy === "unresolved") {
    return fallback || "UNRESOLVED";
  }
  if (resolved.strategy === "text" || resolved.name) {
    return resolved.name ?? resolved.value;
  }
  if (resolved.strategy === "testid") {
    return `id:${resolved.value}`;
  }
  return resolved.value;
};

const emitStep = (step: IntermediateAction): string[] => {
  switch (step.action) {
    case "setup":
      return [`- runFlow:`, `    file: setup.yaml # ${step.description}`];
    case "tap":
    case "click":
      return [`- tapOn: ${JSON.stringify(maestroSelector(step.resolved, step.target))}`];
    case "wait":
      return [`- extendedWaitUntil:`, `    timeout: ${step.timeoutMs}`];
    case "assert":
      if (
        step.assert === "elementVisible" ||
        step.assert === "elementText" ||
        step.assert === "elementInViewport"
      ) {
        return [
          `- assertVisible: ${JSON.stringify(maestroSelector(step.resolved, step.target))}`,
        ];
      }
      return [`# assert ${step.assert}: ${step.target}`];
    case "http":
      return [
        `# HTTP ${step.method} ${step.path} is exercised via the api/web harness, not Maestro`,
      ];
    default:
      return [`# unsupported`];
  }
};

/**
 * Emits one Maestro flow YAML per scenario (iOS surface).
 * Returns a map of filename → contents.
 */
export const emitMaestro = (
  form: IntermediateForm
): Record<string, string> => {
  const files: Record<string, string> = {};

  if (!form.surfaces.includes("ios") && form.layer !== "mobile") {
    return files;
  }

  for (const scenario of form.scenarios) {
    const lines = [
      `appId: \${APP_ID}`,
      `---`,
      `# GENERATED by Corin compiler — do not edit by hand.`,
      `# Spec: ${form.specId}@v${form.specVersion} / ${scenario.id}`,
      `# Seed: ${form.seed}`,
      ``,
      `- launchApp`,
    ];
    for (const step of scenario.steps) {
      lines.push(...emitStep(step));
    }
    lines.push(``);
    files[`${form.specId}-${scenario.id.toLowerCase()}.yaml`] = lines.join("\n");
  }

  return files;
};
