import type { IntermediateForm, IntermediateAction, ResolvedTarget } from "../types";

const locatorExpr = (resolved?: ResolvedTarget): string => {
  if (!resolved || resolved.strategy === "unresolved") {
    return `page.getByText("UNRESOLVED") /* unresolved: needs LLM target resolution */`;
  }
  switch (resolved.strategy) {
    case "role":
      return `page.getByRole(${JSON.stringify(resolved.value)}, { name: ${JSON.stringify(resolved.name ?? resolved.value)} })`;
    case "text":
      return `page.getByText(${JSON.stringify(resolved.value)})`;
    case "testid":
      return `page.getByTestId(${JSON.stringify(resolved.value)})`;
    case "css":
      return `page.locator(${JSON.stringify(resolved.value)})`;
    default:
      return `page.locator('body')`;
  }
};

const emitStep = (step: IntermediateAction, indent: string): string[] => {
  switch (step.action) {
    case "setup":
      return [
        `${indent}// Setup: ${step.description}`,
        step.fixture
          ? `${indent}const fixture = ${JSON.stringify(step.fixture)} as const;\n${indent}void fixture;`
          : `${indent}// Preconditions must already hold in the test environment.`,
      ];
    case "tap":
    case "click":
      return [`${indent}await ${locatorExpr(step.resolved)}.click();`];
    case "wait":
      return [
        `${indent}await page.waitForTimeout(${step.timeoutMs}); // ${step.reason}`,
      ];
    case "http": {
      const opts =
        step.body != null
          ? `, { data: ${JSON.stringify(step.body)} }`
          : "";
      return [
        `${indent}const response = await request.${step.method.toLowerCase()}(${JSON.stringify(step.path)}${opts});`,
      ];
    }
    case "assert": {
      if (step.assert === "httpStatus") {
        return [
          `${indent}expect(response.status()).toBe(${JSON.stringify(step.expected)});`,
        ];
      }
      if (step.assert === "httpBody") {
        return [
          `${indent}// Body expectation from spec: ${step.target}`,
          `${indent}const body = await response.json();`,
          `${indent}expect(body).toBeTruthy();`,
        ];
      }
      if (step.assert === "noPartialState") {
        return [
          `${indent}// Assert no partial join/mutation left behind: ${step.target}`,
        ];
      }
      if (step.assert === "elementInViewport") {
        return [
          `${indent}{`,
          `${indent}  const box = await ${locatorExpr(step.resolved)}.boundingBox();`,
          `${indent}  expect(box).not.toBeNull();`,
          `${indent}  const viewport = page.viewportSize();`,
          `${indent}  expect(viewport).not.toBeNull();`,
          `${indent}  if (box && viewport) {`,
          `${indent}    expect(box.x).toBeGreaterThanOrEqual(0);`,
          `${indent}    expect(box.y).toBeGreaterThanOrEqual(0);`,
          `${indent}    expect(box.x + box.width).toBeLessThanOrEqual(viewport.width);`,
          `${indent}    expect(box.y + box.height).toBeLessThanOrEqual(viewport.height);`,
          `${indent}  }`,
          `${indent}}`,
        ];
      }
      const visibility =
        step.timeoutMs != null
          ? `await expect(${locatorExpr(step.resolved)}).toBeVisible({ timeout: ${step.timeoutMs} });`
          : `await expect(${locatorExpr(step.resolved)}).toBeVisible();`;
      return [`${indent}${visibility}`];
    }
    default:
      return [`${indent}// unsupported step`];
  }
};

export const emitPlaywright = (form: IntermediateForm): string => {
  const lines: string[] = [
    `/**`,
    ` * GENERATED by Corin compiler — do not edit by hand.`,
    ` * Spec: ${form.specId}@v${form.specVersion}`,
    ` * Seed: ${form.seed}`,
    ` * Compiled: ${form.compiledAt}`,
    ` */`,
    `import { test, expect } from "@playwright/test";`,
    ``,
    `const concrete = ${JSON.stringify(form.concreteValues, null, 2)} as const;`,
    ``,
  ];

  for (const scenario of form.scenarios) {
    const title = `${scenario.id} — ${scenario.title}`;
    const useRequest = scenario.steps.some((s) => s.action === "http");
    const usePage = scenario.steps.some(
      (s) =>
        s.action === "tap" ||
        s.action === "click" ||
        s.action === "wait" ||
        (s.action === "assert" &&
          (s.assert === "elementVisible" ||
            s.assert === "elementText" ||
            s.assert === "elementInViewport"))
    );
    const fixtures = [
      usePage ? "page" : null,
      useRequest ? "request" : null,
    ].filter(Boolean);
    const fixtureArgs = fixtures.length ? `{ ${fixtures.join(", ")} }` : "{}";
    lines.push(`test(${JSON.stringify(title)}, async (${fixtureArgs}) => {`);
    lines.push(`  void concrete;`);
    for (const step of scenario.steps) {
      lines.push(...emitStep(step, "  "));
    }
    lines.push(`});`);
    lines.push(``);
  }

  return lines.join("\n");
};
